name: Increment Version on Develop

on:
  push:
    branches:
      - develop

jobs:
  increment-version:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'  # or '5.x' if your project targets .NET 5 or later

      - name: Get current version
        id: get_version
        run: echo "::set-output name=version::$(dotnet --version)"

      - name: Increment version
        id: increment_version
        run: |
          # Assuming you're using Semantic Versioning (Major.Minor.Patch)
          $currentVersion = "${{ steps.get_version.outputs.version }}"
          $versionParts = $currentVersion -split '\.'
          $newVersion = "$($versionParts[0]).$($versionParts[1] + 1).$($versionParts[2])"
          echo "##vso[task.setvariable variable=new_version;isOutput=true]$newVersion"

      - name: Update version in files
        run: |
          # Update version in your project files (e.g., csproj, package.json)
          (Get-Content D:\git\HxcApi\HxcApi\HxcApi\HxcApi.csproj) -replace '<Version>.*<\/Version>', "<Version>${{ steps.increment_version.outputs.new_version }}</Version>" | Set-Content  D:\git\HxcApi\HxcApi\HxcApi\HxcApi.csproj


      - name: Commit version increment
        run: |
          git add  D:\git\HxcApi\HxcApi\HxcApi\HxcApi.csproj
          git commit -m "Increment version to ${{ steps.increment_version.outputs.new_version }}"

      - name: Push changes
        run: |
          git push origin develop
