name: Test App

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'  # or the version you are using

      - name: Restore dependencies and run tests
        run: |
          cd HxcApi
          dotnet restore
          dotnet test --filter TestCategory!=IntegrationTest
