name: Test the app

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'
          
      - name: Restore dependencies
        working-directory: ./HxcApi/HxcApi
        run: dotnet restore

      - name: Build and test
        working-directory: ./HxcApi/HxcApi
        run: dotnet test --filter TestCategory!=IntegrationTest

